//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdfundingPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Award
    {
        public Award()
        {
            this.Basket = new HashSet<Basket>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ProjectId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<float> Price { get; set; }
        public Nullable<int> Qty { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ICollection<Basket> Basket { get; set; }
    }
}
