//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdfundingPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public System.Guid Id { get; set; }
        public string UserLogin { get; set; }
        public System.Guid AwardId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<float> Price { get; set; }
    
        public virtual Award Award { get; set; }
        public virtual User User { get; set; }
    }
}
