//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdfundingPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Award = new HashSet<Award>();
            this.Transaction = new HashSet<Transaction>();
        }
    
        public System.Guid Id { get; set; }
        public string Owner { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<float> RequiredAmount { get; set; }
        public Nullable<float> CurrentAmount { get; set; }
        public Nullable<int> Status { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Award> Award { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Transaction> Transaction { get; set; }
    }
}
